// Generated by https://quicktype.io

import 'package:appnew/models/actor_model.dart';

class PopularModel {
  bool? adult;
  String? backdropPath;
  List<genresModel>? genre;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;
  List<Actor> actors; // Lista de actores
  String? trailerUrl;

  PopularModel({
    this.adult,
    this.backdropPath,
    required this.genre,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
    required this.actors, // Debes incluir la lista de actores en el constructor
    required this.trailerUrl,
  });
  factory PopularModel.fromMap(Map<String, dynamic> movie) {
    return PopularModel(
      id: movie['id'],
      backdropPath: movie['backdrop_path'],
      posterPath: movie['poster_path'],
      originalLanguage: movie['original_language'],
      overview: movie['overview'],
      popularity: movie['popularity'],
      releaseDate: movie['release_date'],
      title: movie['title'],
      voteAverage: movie['vote_average'],
      voteCount: movie['vote_count'],
      genre: [],
      actors: [],
      trailerUrl: movie['trailerUrl'] ?? '',
    );
  }
}

class genresModel {
  int? id;
  String? name;

  genresModel({
    this.id,
    this.name,
  });

  factory genresModel.fromMap(Map<String, dynamic> genres) {
    return genresModel(
      id: genres['id'],
      name: genres['name'],
    );
  }
}
